---
title: "DD_fmri"
author: "Sophie Fromm"
date: "14 6 2021"
output: word_document
theme: yeti
#bibliography: lib_DD.bib
---

```{r setup_loadData, include=FALSE}
rm(list=ls())

## Preparations - Load  packages and data 
library(readxl)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(knitr)
library(kableExtra)
library(emmeans)
library(lsmeans)
library(afex)
library(Rfit)
library(janitor)
library(Hmisc)
library(DescTools)
library(rstatix)
library(car)
library(PerformanceAnalytics)

#round to 2 and pvalues to 3 digits after comma
options(scipen = 1, digits = 2)
f_pvalue = function(p.value, symbol = "="){
  p.value <- round(p.value, digits = 3)
  if (p.value <.001) {
    return("p < .001")
  } else {
    return(paste0("p", symbol, round(p.value, digits = 3)))
  }
}
```

```{r LoadData, include=FALSE}
#Load data n = 86
DD_data_all <- readxl::read_excel("RDD_clean_alldata.xlsx")

#Create groups
DD_data_all$cat_group <- as.integer(as.factor(DD_data_all$group_DD))
mapping <- c("1" = "HC", "2" = "HC+D", "3" = "PSZ","4" = "PSZ+D")
DD_data_all$cat_group<- mapping[DD_data_all$cat_group]

#factorize Illness and Delusion
DD_data_all$fIllness <-factor(DD_data_all$Illness)
DD_data_all$fDelusion <-factor(DD_data_all$Delusion)
```

```{r selectSamples, include=FALSE}
#aborted trajectories results in n = 82 Code!="sz_10_014" & Code!="sz_20_123" & Code!="sz_20_136" & Code!= "sz_20_196"
#Nonfitter results in n = 66
DD_data_fitter<-filter(DD_data, Code!="sz_10_014" & Code!="sz_20_123" & Code!="sz_20_136" & Code!= "sz_20_196", Code!="sz_20_178" & Code!='sz_20_194' & Code!='sz_20_195' & Code!='sz_00_022'& Code!="sz_00_083" & Code!="sz_10_020" &  Code!='sz_10_033'& Code!='sz_10_036'& Code!="sz_10_050"  & Code!='sz_20_023'  & Code!="sz_20_082" & Code!="sz_20_087" & Code!='sz_20_092'& Code!='sz_20_120' & Code!="sz_20_154" &  Code!='sz_20_158')
#& Code!='sz_20_035' & Code!="sz_20_124" & Code!='sz_20_108' & Code!='sz_00_102')Code!='sz_20_182'  &

#long format
DD_data_long<-gather(DD_data, parameter_type, parameter_value,  M6_kappa:M6_beta)
DD_data_long_fitter <-gather(DD_data_fitter, parameter_type, parameter_value,  M6_kappa:M6_beta)
```


```{r scatter, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# single scatter plot example
ggscatter(data = DD_data_fitter,x = "M6_beta", y = "M6_m3",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "beta", ylab = "m3")
```
## Violines

```{r `violine`, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# m3
par(mfrow=c(3,3))
pm3_fitter = ggplot(data = DD_data_fitter, aes(x = cat_group, y = M6_m3, fill = cat_group)) +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab('m3')  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")

# beta
pbeta_fitter = ggplot(data = DD_data_fitter, aes(x = cat_group, y = M6_beta, fill = cat_group))  +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab('β')  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")
 
# mu3_0
pmu3_0_fitter= ggplot(data = DD_data, aes(x = cat_group, y = M6_mu_0, fill = cat_group))  +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab(expression('μ3'^'(k=0)'))  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")
dev.off()
 
# theta
ptheta_fitter= ggplot(data = DD_data_fitter, aes(x = cat_group, y = M6_theta, fill = cat_group)) +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab('ϑ')  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")
dev.off
# omega
pomega_fitter= ggplot(data = DD_data_fitter, aes(x = cat_group, y = M6_omega, fill = cat_group)) +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab('ω')  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")
# kappa
pkappa_fitter= ggplot(data = DD_data_fitter, aes(x = cat_group, y = M6_kappa, fill = cat_group)) +  geom_violin(trim = FALSE) +   scale_fill_brewer(palette = "Paired") + labs(fill = "Group") + xlab("Group") + ylab('κ')  + stat_summary(fun.data=mean_sdl, geom="errorbar", color="red", width = .2) +  geom_jitter(dotsize = 0.5, fill = "black", height = 0, width = .06, alpha = .5)  + theme_classic(base_size = 20)+ stat_summary(fun=mean, geom="point", color="red") + theme(legend.position = "none")

png("grid_params_all_fitter.png")
grid.arrange(pm3_fitter, pbeta_fitter, ptheta_fitter, pomega_fitter, pkappa_fitter, nrow = 3)
 dev.off()
 
tiff('grid_params_all_fitter.tiff', units="in", width=10, height=10, res=300, compression = 'lzw')
grid.arrange(pm3_fitter, pbeta_fitter, ptheta_fitter, pomega_fitter, pkappa_fitter, nrow = 3)
dev.off()

# correlate with behav
vars_to_check <- DD_data_fitter[, c(4:10, 32, 37, 40, 41)] #kappa until beta behav
tiff('grid_params_behav.tiff', units="in", width=10, height=10, res=300, compression = 'lzw')
chart.Correlation(vars_to_check)
dev.off()
# np and behav
vars_to_check <- DD_data_fitter[, c(32, 37, 40, 41, 59, 61:65)] #kappa until beta with np

# and np
vars_to_check <- DD_data_fitter[, c(4:10, 59, 61:65)] #kappa until beta with np
tiff('grid_params_NP.tiff', units="in", width=10, height=10, res=300, compression = 'lzw')
chart.Correlation(vars_to_check)
 dev.off()

```


## Mu3 Trajectories

```{r mu3_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# make table with mean per phase
gd <- DD_data_fitter %>%  gather(phase, mu3_traj, mu3_pre:mu3_post) %>%
        group_by(cat_group, phase) %>% summarise(mu3_traj = mean(mu3_traj))

#rearrange the order
new_gd = gd %>% arrange(match(phase, c("mu3_pre", "mu3_vol", "mu3_post")))

m3_plot <- DD_data_fitter %>% gather(phase, mu3_traj, mu3_pre:mu3_post) %>% ggplot(aes(x=phase, y=mu3_traj, color=cat_group))  +  geom_jitter(width = .2, alpha = .3, size = 4, shape = 16)  +theme_classic() + geom_jitter(data = gd, shape = 15, size = 6, show.legend = FALSE, width = .1) +  labs(color = "Groups") + ylab("µ3") +theme_classic(base_size = 20)

#save as png
png("mu3_phase.png")
mu3<-m3_plot + scale_x_discrete(limits=c("mu3_pre","mu3_vol", "mu3_post"), labels=c("stable pre", "volatile", "stable post")) +scale_color_manual(values=c("dodgerblue4",  "navy","YellowGreen", "darkgreen")) + geom_path(data = new_gd, aes(x = phase, y = mu3_traj, group = cat_group))+ theme(legend.position = "none")
dev.off()

```
## yeu Trajectories predicted environmetnal uncertainty

```{r yeu2_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# make table with mean per phase
gd <- DD_data_fitter %>%  gather(phase, yeu_traj, yeu_pre:yeu_post) %>%
        group_by(cat_group, phase) %>% summarise(yeu_traj = mean(yeu_traj))

#rearrange
new_gd = gd %>% arrange(match(phase, c("yeu_pre", "yeu_vol", "yeu_post")))

yeu_plot <- DD_data_fitter %>% gather(phase, yeu_traj, yeu_pre:yeu_post) %>% ggplot(aes(x=phase, y=yeu_traj, color=cat_group))  +  geom_jitter(width = .2, alpha = .3, size = 4, shape = 16)+theme_classic() + geom_jitter(data = gd, shape = 15, size = 6, show.legend = FALSE, width = .1) +  labs(color = "Groups") + ylab("γ2")+  theme_classic(base_size = 20)

#save as png
png("yeu_phase.png")
yeu<-yeu_plot + scale_color_manual(values=c("dodgerblue4",  "navy","YellowGreen", "darkgreen")) + geom_path(data = new_gd, aes(x = phase, y = yeu_traj, group = cat_group))+ theme(legend.position = "none") + scale_x_discrete(limits=c("yeu_pre","yeu_vol", "yeu_post"), labels=c("stable pre", "volatile", "stable post"))
dev.off()

```
## Sa2 Trajectories predicted outcoe uncertainty

```{r σ2_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# make table with mean per phase
gd <- DD_data_fitter %>%  gather(phase, sa2_traj, sa2_pre:sa2_post) %>%
        group_by(cat_group, phase) %>% summarise(sa2_traj = mean(sa2_traj))

#rearrange
new_gd = gd %>% arrange(match(phase, c("sa2_pre", "sa2_vol", "sa2_post")))

sa2_plot <- DD_data_fitter %>% gather(phase, sa2_traj, sa2_pre:sa2_post) %>% ggplot(aes(x=phase, y=sa2_traj, color=cat_group))  +  geom_jitter(width = .2, alpha = .3, size = 4, shape = 16)+theme_classic() + geom_jitter(data = gd, shape = 15, size = 6, show.legend = FALSE, width = .1) +  labs(color = "Groups") + ylab("σ2")+  theme_classic(base_size = 20)

#save as png
png("sa2_phase.png")
sa2<-sa2_plot + scale_color_manual(values=c("dodgerblue4",  "navy","YellowGreen", "darkgreen")) + geom_path(data = new_gd, aes(x = phase, y = sa2_traj, group = cat_group))+ theme(legend.position = "none") + scale_x_discrete(limits=c("sa2_pre","sa2_vol", "sa2_post"), labels=c("stable pre", "volatile", "stable post"))
dev.off()

```

## Epsi2 Trajectories

```{r Ɛ2_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# make table with mean per phase
gd <- DD_data_fitter %>%  gather(phase, epsi2_traj, epsi2_pre:epsi2_post) %>%
        group_by(cat_group, phase) %>% summarise(epsi2_traj = mean(epsi2_traj))

#rearrange (rev is equal to the volatility phase here)
new_gd = gd %>% arrange(match(phase, c("epsi2_pre", "epsi2_vol", "epsi2_post")))

eps2_plot <- DD_data_fitter %>% gather(phase,  epsi2_traj, epsi2_pre:epsi2_post) %>% ggplot(aes(x=phase, y=epsi2_traj, color=cat_group))  +  geom_jitter(width = .2, alpha = .3, size = 4, shape = 16)+theme_classic() + geom_jitter(data = gd, shape = 15, size = 6, show.legend = FALSE, width = .1) +  labs(color = "Groups") + ylab("Ɛ2")+  theme_classic(base_size = 20) +theme(legend.position = "none")

#save as png
png("eps2_phase.png")
e2<-eps2_plot + scale_color_manual(values=c("dodgerblue4",  "navy","YellowGreen", "darkgreen")) + geom_path(data = new_gd, aes(x = phase, y = epsi2_traj, group = cat_group))+ scale_x_discrete(limits=c("epsi2_pre", "epsi2_vol", "epsi2_post"), labels=c("stable pre", "volatile", "stable post"))
dev.off()

```

## Epsi3 Trajectories

```{r Ɛ3_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# make table with mean per phase
gd <- DD_data_fitter %>%  gather(phase, epsi3_traj, epsi3_pre:epsi3_post) %>%
        group_by(cat_group, phase) %>% summarise(epsi3_traj = mean(epsi3_traj))

#rearrange 
new_gd = gd %>% arrange(match(phase, c("epsi3_pre", "epsi3_vol", "epsi3_post")))

eps3_plot <- DD_data_fitter %>% gather(phase,  epsi3_traj, epsi3_pre:epsi3_post) %>% ggplot(aes(x=phase, y=epsi3_traj, color=cat_group))  +  geom_jitter(width = .2, alpha = .3, size = 4, shape = 16)+theme_classic() + geom_jitter(data = gd, shape = 15, size = 6, show.legend = FALSE, width = .1) +  labs(color = "Groups") + ylab("Ɛ3")+  theme_classic(base_size = 20)

#save as png
png("eps3_phase.png")
e3<-eps3_plot + scale_color_manual(values=c("dodgerblue4",  "navy","YellowGreen", "darkgreen")) + geom_path(data = new_gd, aes(x = phase, y = epsi3_traj, group = cat_group))+ theme(legend.position = "none") + scale_x_discrete(limits=c("epsi3_pre", "epsi3_vol", "epsi3_post"), labels=c("stable pre", "volatile", "stable post"))
dev.off()


tiff('traj_figure.tiff', units="in", width=10, height=20, res=300, compression = 'lzw')
ggarrange(mu3, sa2, e2, e3, yeu, labels = c("A", "B", "C"), ncol = 1, nrow = 5)
dev.off()

```