```{r setup_loadData, include=FALSE}
rm(list=ls())

## Preparations - Load  packages and data 
library(readxl)
library(tidyverse)
library(ggpubr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(knitr)
library(kableExtra)
library(emmeans)
library(lsmeans)
library(afex)
library(Rfit)
library(janitor)
library(Hmisc)
library(DescTools)
library(rstatix)
library(car)
library(PerformanceAnalytics)

#round to 2 and pvalues to 3 digits after comma
options(scipen = 1, digits = 2)
f_pvalue = function(p.value, symbol = "="){
  p.value <- round(p.value, digits = 3)
  if (p.value <.001) {
    return("p < .001")
  } else {
    return(paste0("p", symbol, round(p.value, digits = 3)))
  }
}
```
## Load Data
```{r LoadData, include=FALSE}
#Load data n = 86
DD_data_all <- readxl::read_excel("RDD_clean_alldata.xlsx")

#Create groups
DD_data_all$cat_group <- as.integer(as.factor(DD_data_all$group_DD))
mapping <- c("1" = "HC", "2" = "HC+D", "3" = "SZ","4" = "SZ+D")
DD_data_all$cat_group<- mapping[DD_data_all$cat_group]

#factorize Illness and Delusion
DD_data_all$fIllness <-factor(DD_data_all$Illness)
DD_data_all$fDelusion <-factor(DD_data_all$Delusion)
```
## Select fitter / non-fitter by ID
```{r selectSamples, include=FALSE}
#aborted trajectories results in n = 82 Code!="sz_10_014" & Code!="sz_20_123" & Code!="sz_20_136" & Code!= "sz_20_196"

#Subs with good model-fit n = 66
DD_data_fitter<-filter(DD_data_all, Code!="sz_10_014" & Code!="sz_20_123" & Code!="sz_20_136" & Code!= "sz_20_196" & Code!="sz_20_178" & Code!='sz_20_194' & Code!='sz_20_195' & Code!='sz_00_022'& Code!="sz_00_083" & Code!="sz_10_020" &  Code!='sz_10_033'& Code!='sz_10_036'& Code!="sz_10_050"  & Code!='sz_20_023'  & Code!="sz_20_082" & Code!="sz_20_087" & Code!='sz_20_092'& Code!='sz_20_120' & Code!="sz_20_154" &  Code!='sz_20_158')
#& Code!='sz_20_035' & Code!="sz_20_124" & Code!='sz_20_108' & Code!='sz_00_102')Code!='sz_20_182'  &

#Subs without good model-fit n = 20
DD_data_nonfitter <- filter(DD_data_all, Code=="sz_10_014"| Code=="sz_20_123" | Code=="sz_20_136" | Code== "sz_20_196" | Code=="sz_20_178" | Code=='sz_20_194' | Code=='sz_20_195' | Code=='sz_00_022'| Code=="sz_00_083" | Code=="sz_10_020" |  Code=='sz_10_033'| Code=='sz_10_036'| Code=="sz_10_050"  | Code=='sz_20_023'  | Code=="sz_20_082" | Code=="sz_20_087" | Code=='sz_20_092'| Code=='sz_20_120' | Code=="sz_20_154" |  Code=='sz_20_158')

#Long format
DD_data_long<-gather(DD_data_all, parameter_type, parameter_value,  M6_kappa:M6_beta)
DD_data_long_fitter <-gather(DD_data_fitter, parameter_type, parameter_value,  M6_kappa:M6_beta)
```
## Descriptive stats on demo, cog, clin, behav variables
```{r Descriptives, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE }
options(digits = 3)
# Descriptive stats raw behavior
behav <- group_by(DD_data_fitter, group_DD) %>%
  summarise_at(vars(CorrectPerc, p_stay, p_w_st, p_l_sw, Alter), funs(mean, sd))
#Descriptive stats of clinical and cognitive variables
clinical <-group_by(DD_data_fitter, group_DD) %>%
  summarise_at(vars(Alter, PDIGesamt, PANSS_total, PANSS_pos_sum, PANSS_neg_sum, PANNS_gp_sum, CPZ), funs(mean, sd), na.rm = TRUE)
cognitive <- group_by(DD_data_fitter, group_DD) %>%
  summarise_at(vars(WST_raw,Wortliste,Digit_Span,TM_Asek,TM_Bsek,DSST), funs(mean, sd), na.rm = TRUE)
# Descriptive stats model parameter
params <- group_by(DD_data_fitter, cat_group) %>%
  summarise_at(vars(M6_kappa, M6_omega, M6_theta, M6_beta, M6_m3, M6_mu_0), funs(mean, sd))
``` 
## Test stats on demo, cog, clin, behav variables
```{r Test-stats, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE }
#Age ANOVA
 aov.age<-DD_data_all %>% 
  aov_ez(
    data = .,
    dv = "Alter",
    id = "Code",
    between = c("Illness", "Delusion"))

# Correct responses across phases
mm.corr_perc<- DD_data_long_fitter %>% gather(phase, correct, Correct_pre:Correct_post) %>% 
  aov_ez(
     data = .,
     dv = "correct",
     id = "Code",
     within="phase",
     between = c("fIllness", "fDelusion")  )

# post-hoc tests for correct responses
correct_phase<- emmeans(mm.corr_perc, c("phase"))
correct_Illness<- emmeans(mm.corr_perc, c("fIllness"))
ref_df <- as.data.frame(summary(correct_phase))
contrast(correct_Illness, method="pairwise") # uses tukey adjustment for multiple testing
contrast(correct_phase, method="pairwise")

#2x2 anova on stay-switch behavior (no phases)
formulae <- lapply(colnames(DD_data_fitter)[37:42], function(x) as.formula(paste0("dv= '",x,"'")))
ANOVA_one <- lapply(formulae, function(x) afex::aov_ez(data = DD_data_fitter, x, id = "Code", between = c("fIllness","fDelusion"))) #covariate = "Alter", factorize = 0))

#Example how to check anova assumptions
#Normality
vars_to_check <- DD_data_fitter[37:42] #example for stay-switch behavior
apply(vars_to_check, MARGIN = 2,  FUN = function(x) shapiro.test(x))
#Extreme values
apply(vars_to_check, MARGIN = 2,  FUN = function(x) sum(is_extreme(x)))
#Example Histogram for m3
hist(DD_data_fitter$M6_m3, breaks = 20)

# CLINICAL 1 sub MISSING
#Manova and post-hoc anovas with illness x delusion
DD_data_fitter_SZ <- subset(DD_data_fitter,Illness==1)
DD_data_nonfitter_SZ <- subset(DD_data_nonfitter,Illness==1)
clin.man_SZ <- manova(cbind(PANSS_total, PANSS_pos_sum, PANSS_neg_sum, PANNS_gp_sum, CPZ) ~ Delusion, data = DD_data_fitter_SZ)
summary.aov(clin.man_SZ) 
summary(clin.man_SZ, test = "Wilks")

## Post hoc PDI
DD_data_fitter_HC <- subset(DD_data_fitter,Illness==0)
clin.man_HC <-aov(PDIGesamt ~ Delusion, data = DD_data_fitter_HC)
summary.aov(clin.man_HC) 
#summary(clin.man_hC, test = "Wilks")

#COGNITIVE 2 subs MISSING
#Manova on cognitive variables and post-hoc anovas with illness x delusion
cog.man <- manova(cbind(WST_raw,Wortliste,Digit_Span,TM_Asek,TM_Bsek,DSST) ~ Illness*Delusion, data = DD_data_fitter)
summary.aov(cog.man) 
summary(cog.man, test = "Wilks")

#For supplement compare fitter and nonfitter SZ
res.PANSS<-t.test(DD_data_fitter_SZ$PANSS_total, DD_data_nonfitter_SZ$PANSS_total, alternative = "two.sided")
res.ALTER<-t.test(DD_data_fitter_SZ$Alter, DD_data_nonfitter_SZ$Alter, alternative = "two.sided")
res.CPZ<-t.test(DD_data_fitter_SZ$CPZ, DD_data_nonfitter_SZ$CPZ, alternative = "two.sided")
res.CORRECT <- t.test(DD_data_fitter_SZ$CorrectPerc, DD_data_nonfitter_SZ$CorrectPerc, alternative = "two.sided")
res.winst<- t.test(DD_data_fitter_SZ$p_w_st, DD_data_nonfitter_SZ$p_w_st, alternative = "two.sided")
res.losw<-t.test(DD_data_fitter_SZ$p_l_st, DD_data_nonfitter_SZ$p_l_st, alternative = "two.sided")

#Explore correlations between parameters
#chart.corrs_new <-  chart.Correlation(DD_data_fitter %>% select((M6_kappa:M6_beta), histogram=TRUE, pch=19))

# make little table
#t(params) %>%
#  kbl(caption = "Summary modeling parameters") %>%
#  kable_classic(full_width = F, html_font = "Times New Roman")
  
```
## MANOVA and post-hoc ANOVAs on model params to compare between groups (Illness x Delusion)
```{r parameter_MANOVA, echo=FALSE, warning=FALSE, message= FALSE, error = FALSE}
#2.	One-way ANOVA between CHR and HC on all parameters
#Manova on model params --> main effect of illness and delusion, no interaction
params.man <- manova(cbind(M6_kappa, M6_omega, M6_theta, M6_beta, M6_mu_0, M6_m3) ~ Delusion * Illness, data = DD_data_fitter)
summary.aov(params.man) 
summary(params.man, test = "Wilks")

# Post hoc ANOVAs on individual model parameters
formulae <- lapply(colnames(DD_data_fitter)[4:10], function(x) as.formula(paste0("dv= '",x,"'")))
ANOVA_one <- lapply(formulae, function(x) afex::aov_ez(data = DD_data_fitter, x, id = "Code", between = c("Illness", "Delusion")))
#names(ANOVA_one) <- format(formulae)
#F_val <-lapply(names(ANOVA_one), function(x){ANOVA_one[[x]][["anova_table"]][["F"]]})

# -- Unstructured section  to check ANOVA assumptions
# Check ANOVA assumptions; spread of all groups in plot 1 and 3 similar?
# plot linear model from ANOVA
par(mfrow=c(2,2))
plot(ANOVA_one[[1]][["lm"]]) # do that for all ANOVAs an enter index manually (1-7)
# Shapiro to check normality
Alter <-array(DD_data_fitter$Alter)
vars_to_check <- DD_data_fitter[4:10] #kappa until beta
apply(vars_to_check, MARGIN = 2,  FUN = function(x) shapiro.test(x))
# Outliers: check number of extreme values (>3SD)
apply(vars_to_check, MARGIN = 2,  FUN = function(x) sum(is_extreme(x)))
# -> yes, many have outliers and omega, theta have extreme values (sigma not analyzed)
#omega - not so bad
o <- print(identify_outliers(as.data.frame(DD_data$M6_omega)))
plot(DD_data$M6_omega)
outliervals = o$`DD_data$M6_omega`[o$is.extreme]
DD_data_omex <- DD_data[DD_data$M6_omega!=outliervals[1] & DD_data$M6_omega!=outliervals[2], ]
#theta
th <- identify_outliers(as.data.frame(DD_data$M6_theta))
plot(DD_data$M6_theta)
outliervals = o$`DD_data$M6_omega`[o$is.extreme]
DD_data_thex <- DD_data[DD_data$M6_theta!=outliervals[1] & DD_data$M6_theta!=outliervals[2], ]
#2. Levenes test for sphericity, omega is not homoscedastic
#apply(vars_to_check, MARGIN = 2,  FUN = function(x) leveneTest(residuals(ANOVA_one$x), center = mean))
# Cooks Distance larger than 4/82?
sum(cooks.distance(ANOVA_one$M6_beta$lm)>.049)#mean(DD_data$M6_beta)*3)
plot(ANOVA_one$M6_beta$lm,4)
#plot residuals
PlotQQ(residuals(ANOVA_one$M6_beta))
#check normality of residuals
ols_test_normality(residuals(ANOVA_one$M6_beta))

#---------------------------------------- this is all not great, therefore --> robust anova
vars_to_check <- DD_data_fitter[4:10]
Anova_one_robust <-apply(vars_to_check, MARGIN = 2,  FUN = function(x) raov(x~fIllness*fDelusion,data=DD_data_fitter))
F_val <-lapply(names(Anova_one_robust), function(x){Anova_one_robust[[x]][["table"]][1:3,4:5]})
F_val <- data.frame(F_val)
F_val.new = F_val[seq(1, ncol(F_val), 2), ]
t(data.frame(F_val.new)) %>%
  kbl(caption = "Summary of demographic and modeling parameters") %>%
  kable_classic(full_width = F, html_font = "Times New Roman")

summary(oneway.rfit(DD_data_fitter$M6_m3, DD_data_fitter$group_DD))

# Significant Illness effects on beta and m3 --> post-hoc test
m3_posthoc<- emmeans(Anova_one_robust$M6_m3, c("fIllness"))
contrast(m3_posthoc)

beta_posthoc<- emmeans(Anova_one_robust$M6_beta, c("fIllness"))
contrast(beta_posthoc)

theta_posthoc<- emmeans(ANOVA_one$M6_theta, c("Delusion"))
contrast(theta_posthoc)

```
## Illness x Delusion x Phase ANOVAs on trial-wise model params
```{r sa2_phase,  echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
#histogram(DD_data_fitter$sa2)
mm.sa2_phase<- DD_data_long_fitter%>%
  gather(phase, sa2_traj, sa2_pre:sa2_post) %>%
  afex::aov_ez(
     data = .,
     dv = "sa2_traj",
     id = "Code",
     within="phase",
     between = c("Illness", "Delusion"))

shapiro.test(residuals(mm.sa2_phase))

# mm suggests significant phase effect - post hoc tests:
sa2phase<- emmeans(mm.sa2_phase, c("phase"))
pairs(sa2phase)
```
```{r mu3_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
# mixed model Illness x Delusion x Phase for mu3(k)
mm.mu3k_phase<- DD_data_long_fitter%>% gather(phase, mu3_traj, mu3_pre:mu3_post) %>% 
  afex::aov_ez(
     data = .,
     dv = "mu3_traj",
     id = "Code",
     within="phase",
     between = c("fIllness", "fDelusion")  ) 

# mm suggests illness and phase effects - post-hoc:
mu3kphase<- emmeans(mm.mu3k_phase, c("phase"))
pairs(mu3kphase)
mu3Illness<- emmeans(mm.mu3k_phase, c("fIllness"))
pairs(mu3Illness)
```
```{r epsi2_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
mm.epsi2_phase<- DD_data_long_fitter %>%gather(phase, epsi2_traj, epsi2_pre:epsi2_post) %>%
  afex::aov_ez(
     data = .,
     dv = "epsi2_traj",
     id = "Code",
     within="phase",
     between = c("fIllness", "fDelusion")  )

e2delphase<- emmeans(mm.epsi2_phase, c("phase", "fDelusion"))
e2phase <-emmeans(mm.epsi2_phase, c("phase"))
contrast(e2phase)
pairs(e2delphase)

plot(e2delphase, by = NULL, comparisons = TRUE, adjust = "mvt", 
     horizontal = FALSE, colors = "darkgreen")
```
```{r epsi3_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
mm.epsi3_phase<- DD_data_long_fitter %>%gather(phase, epsi3_traj, epsi3_pre:epsi3_post) %>%
  afex::aov_ez(
     data = .,
     dv = "epsi3_traj",
     id = "Code",
     within="phase",
     between = c("fIllness", "fDelusion")  )
e3phase <-emmeans(mm.epsi3_phase, c("phase"))
pairs(e3phase)
```
```{r yeu_phase, echo=FALSE, warning=FALSE,  message= FALSE, error = FALSE}
mm.yeu_phase<- DD_data_long_fitter %>%gather(phase, yeu_traj, yeu_pre:yeu_post) %>%
  afex::aov_ez(
     data = .,
     dv = "yeu_traj",
     id = "Code",
     within="phase",
     between = c("fIllness", "fDelusion")  )
y2illphase<- emmeans(mm.yeu_phase, c("phase", "fIllness"))
y2phase<- emmeans(mm.yeu_phase, c("phase"))
y2ill<- emmeans(mm.yeu_phase, c("fIllness"))
pairs(y2ill)
pairs(y2phase)
pairs(y2illphase)
```